// Generated by CoffeeScript 1.8.0
(function() {
  MBooks.IndexRoute = Ember.Route.extend({
    model: function() {
      return this.store.find('link');
    }
  });

}).call(this);

//# sourceMappingURL=index_route.js.map
