// Generated by CoffeeScript 1.8.0
(function() {
  MBooks.IndexView = Ember.View.extend({
    layoutName: "mbooks_container",
    templateName: "index"
  });

}).call(this);

//# sourceMappingURL=views.js.map
